Killing metadata

diff --git a/tracker b/tracker
--- a/tracker
+++ b/tracker
@@ -14,13 +14,67 @@ TRACKER_HELP() {
   echo "             Takes three arguments: The project name, how many hours, and what date (defaults to today)"
 }
 
-TRACKER_DI
+TRACKER_DISPLAY() {
+  if [[ $# -lt 1 ]]; then
+    echo "Invalid number of arguments (expected 1)"
+    exit 2
+  elif [[ ! $1 =~ ^[0-9.]+$ ]]; then
+    echo "Could not parse argument $1 (expected a number)"
+    exit 1
+  fi
+  tracker.py display $1
+}
+
+TRACKER_CREATE() {
+  if [[ $# -lt 1 ]]; then
+    echo "Invalid number of arguments (expected 1)"
+    exit 2
+  elif [[ $1 -z ]]; then
+    echo "Could not parse argument $1 (expected a non-zero string)"
+    exit 1
+  fi
+  tracker.py create $1
+}
+
+TRACKER_ADD() {
+  if [[ $# -lt 2 ]]; then
+    echo "Invalid number of arguments (expected 2)"
+    exit 2
+  elif [[ $1 -z ]]; then
+    echo "Could not parse argument $1 (expected a non-zero string)"
+    exit 1
+  elif [[ ! $2 =~ ^[0-9.]+$ ]]; then
+    echo "Could not parse argument $2 (expected a number)"
+    exit 1
+  elif [[ $# -ge 3 && ! $2 =~ ^[0-9.]+$ ]]; then
+    echo "Could not parse argument $3 (expected a number)"
+    exit 1
+  fi
+  tracker.py add $1 $2 $3
+}
+
+TRACKER_REMOVE() {
+  if [[ $# -lt 2 ]]; then
+    echo "Invalid number of arguments (expected 2)"
+    exit 2
+  elif [[ $1 -z ]]; then
+    echo "Could not parse argument $1 (expected a non-zero string)"
+    exit 1
+  elif [[ ! $2 =~ ^[0-9.]+$ ]]; then
+    echo "Could not parse argument $2 (expected a number)"
+    exit 1
+  elif [[ $# -ge 3 && ! $2 =~ ^[0-9.]+$ ]]; then
+    echo "Could not parse argument $3 (expected a number)"
+    exit 1
+  fi
+  tracker.py remove $1 $2 $3
+}
 
 case $1 in
-  h?(elp    ) HELP;;
-  d?(isplay ) DISPLAY $2;;
-  c?(reate  ) CREATE $2;;
-  a?(dd     ) ADD $2 $3 ${4:-0}
-  r?(emove  ) REMOVE $2 $3 ${4:-0}
+  h?(elp)    ) TRACKER_HELP;;
+  d?(isplay) ) TRACKER_DISPLAY $2;;
+  c?(reate)  ) TRACKER_CREATE $2;;
+  a?(dd)     ) TRACKER_ADD $2 $3 ${4:-0}
+  r?(emove)  ) TRACKER_REMOVE $2 $3 ${4:-0}
 esac
-  
+
